
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  # Configure provisioning
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "start.sh", run: "always"
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"
  end
  